apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: nav-dekoratoren
  namespace: personbruker
  labels:
    team: personbruker
spec:
    unleashInstance:
      apiVersion: unleash.nais.io/v1
      kind: RemoteUnleash
      name: navno
    secretName: nav-dekoratoren-unleash-api-token
    environment: production
